variables:
  IMAGE_URI_BASE: "registry.gitlab.com/signaleleven"
  CI_REGISTRY_TAG: "${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"

stages:
  - build

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t ${IMAGE_URI_BASE}/soundcloud2icecast:${CI_REGISTRY_TAG}
