variables:
  IMAGE_URI_BASE: "registry.gitlab.com/signaleleven"
  CI_REGISTRY_TAG: "${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"

stages:
  - build

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${IMAGE_URI_BASE}/soundcloud2icecast:${CI_REGISTRY_TAG} .
    - docker push  ${IMAGE_URI_BASE}/soundcloud2icecast:${CI_REGISTRY_TAG} 
