version: '2'

services:


  icecast:
    image: infiniteproject/icecast:latest
    restart: always
    environment:
      - 'ICECAST_SOURCE_PASSWORD=icecastpassword'
      - 'ICECAST_ADMIN_PASSWORD=icecastadminpwd'
      - 'ICECAST_RELAY_PASSWORD=icecastrelaypwd'
    ports:
      - '8000:8000'
    networks:
      - radio


  indie_summer:
    image: signaleleven/soundcloud2icecast:latest
    restart: always
    environment:
      - 'ICECAST_PASSWORD=icecastpassword'
      - 'ICECAST_HOST=icecast'
      - 'ICECAST_GENRE=disco'
      - 'SOUNDCLOUD_PLAYLIST=https://soundcloud.com/poolsidefm/sets/indie-summer'
      - 'ICECAST_MOUNTPOINT=/indie_summer'
      - 'ICECAST_STREAM_NAME=PoolsideFM Indie Summer'
      - 'ICECAST_STREAM_DESCRIPTION=A vacation for your mind - indie summer'
    networks:
      - radio

  poolside_fm:
    image: signaleleven/soundcloud2icecast:latest
    restart: always
    environment:
      - 'ICECAST_PASSWORD=icecastpassword'
      - 'ICECAST_HOST=icecast'
      - 'ICECAST_GENRE=ambient'
      - 'ICECAST_MOUNTPOINT=/stream'
      - 'ICECAST_STREAM_NAME=PoolsideFM'
      - 'ICECAST_STREAM_DESCRIPTION=A vacation for your mind'
      - 'SOUNDCLOUD_PLAYLIST=https://soundcloud.com/poolsidefm/sets/poolside-fm-official-playlist'
    networks:
      - radio
        
networks:
  radio:
    driver: bridge
